clientes/urls.py
from django.urls import path, include
from clientes.views import home,clientes,cadastrar_cliente

app_name = 'clientes'

urlpatterns = [
    #Funcionais
    #path('', home, name='home'),
    #path('clientes/',clientes, name='listar'),
    #modificado
    path('',clientes, name='listar'),
    path('cadastrar/',cadastrar_cliente, name= 'cadastrar'),

]

principal/urls.py
from django.contrib import admin
from django.urls import path, include
from clientes.views import home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',include('webloja.urls')),
    #path('',include('clientes.urls')),
    path('', home, name='home'),
    path('produtos/', include('webloja.urls')),
    path('clientes/', include('clientes.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

webloja/urls.py
from django.urls import path, include
from .views import home,produtos,contato,cadastrar_produto

app_name= 'produtos'

urlpatterns = [
    path('', home, name='home'),
    path('faleconosco/',contato, name= 'contato'),
    path('listar/',produtos, name='listar'),
    path('cadastrar/',cadastrar_produto, name= 'cadastrar'),

]

clientes/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Cliente(models.Model):
    Cpf = models.CharField(max_length=11, primary_key=True)
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    cadastrado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)

    
    def __str__(self):
        return self.Cpf

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    TIPO_CHOICES = [
        ('ADMIN', 'Administrador'),
        ('VENDEDOR', 'Vendedor'),
        ('CAIXA', 'Caixa'),
    ]

    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
# Create your models here.

webloja/models.py
from django.db import models
from django.conf import settings

class Produto(models.Model):

    nome = models.CharField(max_length=100)
    categoria = models.CharField(max_length=50)
    quantidade = models.IntegerField()
    preco = models.DecimalField(decimal_places=2, max_digits=5)
    cadastrado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)

    def __str__(self):
        return self.nome
# Create your models here.

clientes/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import ModelForm
from .models import Cliente


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['Cpf', 'nome', 'email']

webloja/forms.py
from django import forms
from django.forms import ModelForm
from .models import Produto

class ContatoForm(forms.Form):
    nome = forms.CharField(
    label="Nome completo",
    max_length=100,
    required=True,
    widget=forms.TextInput(attrs={'placeholder': 'Informe seu nome completo'})
    #help_text="Informe seu nome completo" 
    )
    email = forms.EmailField(
    label="E-mail",
    required=True
    )
    mensagem = forms.CharField(
    label="Mensagem",
    widget=forms.Textarea(attrs={'rows': 4}),
    required=True
    )

class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'categoria', 'quantidade', 'preco']
    def clean_quantidade(self):
        quantidade = self.cleaned_data.get('quantidade')
        if quantidade <= 0:
            raise forms.ValidationError('A quantidade não pode ser negativo, nem igual a zero.')
        return quantidade

clientes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from clientes.models import Cliente
from clientes.forms import ClienteForm
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from clientes.models import Cliente
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
#FBV
def home(request):
    return render(request, "base.html")

@login_required
def clientes(request):
    lista_clientes = Cliente.objects.all()
    contexto = {'clientes': lista_clientes}
    return render(request, "clientes.html",contexto)

@login_required
def cadastrar_cliente(request):
    if request.user.tipo !='ADMIN':
        return HttpResponseForbidden('Apenas Administradores podem cadastrar clientes')
    
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente = form.save(commit=False)
            cliente.cadastrado_por = request.user
            cliente.save()
            return redirect('clientes:listar')
    else:
        form = ClienteForm()
    return render(request, 'cliente_forms.html',
    {'form': form})

#CBV
class ClientesListView(LoginRequiredMixin, ListView):
    template_name = "clientes.html"
    model = Cliente
    context_object_name = "clientes"

class ClientesCreateView(LoginRequiredMixin, CreateView):
    template_name = "cliente_forms.html"
    model = Cliente
    form_class = ClienteForm
    success_url = reverse_lazy("clientes:listar")
    
    def form_valid(self, form):
        form.instance.cadastrado_por = self.request.user
        return super().form_valid(form)
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.tipo != 'ADMIN':
            return HttpResponseForbidden("Você não tem permissão para cadastrar clientes.")
        return super().dispatch(request, *args, **kwargs)

usuarios/views.py
from django.shortcuts import render

# Create your views here.

webloja/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseForbidden
from webloja.models import Produto 
from django import forms
from webloja.forms import ContatoForm, ProdutoForm
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'base.html')

@login_required
def produtos(request):
    lista_produtos = Produto.objects.all()
    return render(request, "produtos.html",{'produtos': lista_produtos})

def contato(request):
    if request.method == 'POST':
        form = ContatoForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form = ContatoForm()
    else:
        form = ContatoForm()
    return render(request, 'contato.html', {'form':form})
    
@login_required
def cadastrar_produto(request):
    if request.user.tipo !='ADMIN':
        return HttpResponseForbidden('Apenas Administradores podem cadastrar produtos')
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            produto = form.save(commit=False)
            produto.cadastrado_por = request.user
            produto.save()
            return redirect('produtos:listar')
    else:
        form = ProdutoForm()
    return render(request, 'produto_forms.html',
    {'form': form})

clientes/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Meu Sistema Django
        {% endblock %}
    </title>

    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            background-color: #f4f6f8;
        }

        header {
            background-color: #7fedb6ff;
            color: white;
            padding: 15px;
        }

        header h1 {
            margin: 0;
        }

        nav {
            background-color: #369946ff;
            padding: 10px;
        }

        nav a {
            color: white;
            margin-right: 15px;
            text-decoration: none;
            font-weight: bold;
        }

        nav a:hover {
            text-decoration: underline;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #e9ecef;
            text-align: center;
            padding: 10px;
            margin-top: 40px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
        }

        table th {
            background-color: #dee2e6;
        }

        table th, table td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }
        .dropdown {
            display: inline-block;
            position: relative;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #1f5fbf;
            min-width: 180px;
            box-shadow: 0px 4px 8px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            display: block;
            padding: 10px;
            color: white;
            text-decoration: none;
        }

        .dropdown-content a:hover {
            background-color: #174a96;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        .logout-form {
    display: inline;
}

.logout-link {
    background: none;
    border: none;
    color: white;
    font-weight: bold;
    cursor: pointer;
    padding: 0;
    margin-right: 15px;
    text-decoration: none;
    font-family: inherit;
    font-size: inherit;
}

.logout-link:hover {
    text-decoration: underline;
}

    </style>
</head>
<body>

    <header>
        <h1>Sistema de Clientes</h1>
    </header>

    <nav>
        <a href="{% url 'produtos:home' %}">Home</a>
        <div class="dropdown">
        <a href="{% url 'produtos:listar' %}">Produtos</a>
            <div class="dropdown-content">
                <a href="{% url 'produtos:listar' %}">Listar Produtos</a>
                {% if user.tipo == 'ADMIN' %}
                <a href="{% url 'produtos:cadastrar' %}">Cadastrar Produto</a>
                {% endif %}
            </div>
        </div>
        <div class="dropdown">
        <a href="{% url 'clientes:listar' %}">Produtos</a>
            <div class="dropdown-content">
                <a href="{% url 'clientes:listar' %}">Clientes</a>
                {% if user.tipo == 'ADMIN' %}
                <a href="{% url 'clientes:cadastrar' %}">Cadastrar Cliente</a>
                {% endif %}
                
            </div>
        </div>
        
        <a href="{% url 'produtos:contato' %}">Contato</a>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}" class="logout-form">
    {% csrf_token %}
    <button type="submit" class="logout-link">Sair</button>
</form>
        {% endif %}
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2026 — Projeto Django</p>
    </footer>

</body>
</html>

clientes/templates/cliente_forms.html
{% extends 'base.html' %}

{% block title %}Cadastro de Clientes{% endblock %}

{% block content %}

<h1>Cadastro de Clientes</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>

{% endblock %}

clientes/templates/clientes.html
{% extends 'base.html' %}

{% block title %}Lista de Clientes{% endblock %}

{% block content %}
<h1>Lista de clientes</h1>

{% if clientes %}
    <table border="1" cellpadding="8" cellspacing="0">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cpf</th>
                <th>email</th>
                <th>Cadastrado por</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
                <tr>
                    <td>{{ cliente.nome }}</td>
                    <td>{{ cliente.Cpf }}</td>
                    <td>{{ cliente.email }}</td>
                    <td>{{ cliente.cadastrado_por }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Nenhum Cliente cadastrado.</p>
{% endif %}

{% endblock %}

webloja/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Meu Sistema Django
        {% endblock %}
    </title>

    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
            background-color: #f4f6f8;
        }

        header {
            background-color: #2c7be5;
            color: white;
            padding: 15px;
        }

        header h1 {
            margin: 0;
        }

        nav {
            background-color: #1f5fbf;
            padding: 10px;
        }

        nav a {
            color: white;
            margin-right: 15px;
            text-decoration: none;
            font-weight: bold;
        }

        nav a:hover {
            text-decoration: underline;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #e9ecef;
            text-align: center;
            padding: 10px;
            margin-top: 40px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
        }

        table th {
            background-color: #dee2e6;
        }

        table th, table td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }
        .dropdown {
            display: inline-block;
            position: relative;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #1f5fbf;
            min-width: 180px;
            box-shadow: 0px 4px 8px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            display: block;
            padding: 10px;
            color: white;
            text-decoration: none;
        }

        .dropdown-content a:hover {
            background-color: #174a96;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        .logout-form {
    display: inline;
}

.logout-link {
    background: none;
    border: none;
    color: white;
    font-weight: bold;
    cursor: pointer;
    padding: 0;
    margin-right: 15px;
    text-decoration: none;
    font-family: inherit;
    font-size: inherit;
}

.logout-link:hover {
    text-decoration: underline;
}

    </style>
</head>
<body>

    <header>
        <h1>Sistema de Produtos</h1>
    </header>

    <nav>
        <a href="{% url 'produtos:home' %}">Home</a>
        <div class="dropdown">
        <a href="{% url 'produtos:listar' %}">Produtos</a>
            <div class="dropdown-content">
                <a href="{% url 'produtos:listar' %}">Listar Produtos</a>
                {% if user.tipo == 'ADMIN' %}
                <a href="{% url 'produtos:cadastrar' %}">Cadastrar Produto</a>
                {% endif %}
            </div>
        </div>
        <div class="dropdown">
        <a href="{% url 'clientes:listar' %}">Clientes</a>
            <div class="dropdown-content">
                <a href="{% url 'clientes:listar' %}">Clientes</a>
                {% if user.tipo == 'ADMIN' %}
                <a href="{% url 'clientes:cadastrar' %}">Cadastrar Cliente</a>
                {% endif %}
                
            </div>
        </div>
        
        <a href="{% url 'produtos:contato' %}">Contato</a>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}" class="logout-form">
            {% csrf_token %}
            <button type="submit" class="logout-link">Sair</button>
            </form>
        {% endif %}
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2025 — Projeto Django</p>
    </footer>

</body>
</html>

webloja/templates/contato.html
{% extends 'base.html' %}

{% block title %}Fale conosco{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>
{% endblock %}

webloja/templates/login.html
{% extends 'base.html' %}

{% block title %}Sistema Tech Informática{% endblock %}

{% block content %}
<h2>Login</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Entrar</button>
</form>
{% endblock %}

webloja/templates/produto_forms.html
{% extends 'base.html' %}

{% block title %}Lista de Produtos do Estoque{% endblock %}

{% block content %}

<h1>Cadastro de Produto</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>

{% endblock %}

webloja/templates/produtos.html
{% extends 'base.html' %}

{% block title %}Lista de Produtos do Estoque{% endblock %}

{% block content %}
<h1>Lista de Produtos</h1>

{% if produtos %}
    <table border="1" cellpadding="8" cellspacing="0">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Quantidade</th>
                <th>Preço (R$)</th>
                <th>Cadastrado por</th>
            </tr>
        </thead>
        <tbody>
            {% for produto in produtos %}
                <tr>
                    <td>{{ produto.nome }}</td>
                    <td>{{ produto.categoria }}</td>
                    <td>{{ produto.quantidade }}</td>
                    <td>{{ produto.preco }}</td>
                    <td>{{ produto.cadastrado_por }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Nenhum produto cadastrado.</p>
{% endif %}

{% endblock %}